# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "%database_charset%"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    IlcfranceOrangetoolsDataBundle:
                         type: annotation
                         dir: %kernel.root_dir%/../src/Ilcfrance/Orangetools/DataBundle/Entity
                         prefix: Ilcfrance\Orangetools\DataBundle\Entity
                         alias: IlcfranceOrangetoolsDataBundle
                naming_strategy: doctrine.orm.naming_strategy.underscore
#                metadata_cache_driver:
#                    type: service
#                    id: doctrine.cache.memcached
#                query_cache_driver:
#                    type: service
#                    id: doctrine.cache.memcached
#                result_cache_driver:
#                    type: service
#                    id: doctrine.cache.memcached
#                second_level_cache:
#                    enabled: true
#                    log_enabled: true
#                    region_cache_driver:
#                        type: service
#                        id: doctrine.cache.memcached
#                    region_lock_lifetime: 10
#                    region_lifetime: 20

