# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.i18n:
       class: Twig_Extensions_Extension_I18n
       tags:
           - { name: twig.extension }

    twig.extension.array:
       class: Twig_Extensions_Extension_Array
       tags:
           - { name: twig.extension }

    twig.extension.string_loader:
       class: Twig_Extension_StringLoader
       tags:
           - { name: twig.extension }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

    memcached:
        class: Memcached
        calls:
            - ["addServers", ['%memcache_hosts%']]

    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - ["setMemcached", ["@memcached"]]

    predis:
        class: Predis\Client

    doctrine.cache.predis:
        class: Doctrine\Common\Cache\PredisCache
        arguments:
            client: "@predis"



