# Redis
snc_redis:
    clients:
        default:
            type: predis
            dsn: %redis_dns%
            alias: default
        session:
            type: predis
            alias: session
            dsn: %redis_dns%
#        swiftmailer:
#            type: predis
#            dsn: %redis_dns%
#            alias: swiftmailer
        cache:
             type: predis
             dsn: %redis_dns%
             alias: cache

    session:
        client: session
        prefix: session:com.ilcfrance.orangetools.
#    swiftmailer:
#        client: swiftmailer
#        key: swiftmailer:com.ilcfrance.orangetools.
#    doctrine:
#        metadata_cache:
#            client: cache
#            entity_manager: ["default"]          # the name of your entity_manager connection
##            document_manager: ["default"]        # the name of your document_manager connection
#        result_cache:
#            client: cache
#            entity_manager: ["default"]  # you may specify multiple entity_managers
#        query_cache:
#            client: cache
#            entity_manager: ["default"]
#        second_level_cache:
#            client: cache
#            entity_manager: ["default"]