parameters:
    schemes: https
    domain: orangetools.ilcfrance.com
    mail_from:                 "system@ilcfrance.com"
    mail_from_name:            "ILCFrance.com"
    sitename:                  "OrangeTools.ILCFrance"
    mailer_transport: sendmail
