<?php

namespace Ilcfrance\Orangetools\DataBundle\EntityRepository;

use Ilcfrance\Orangetools\DataBundle\Entity\Moduleformation;

/**
 * SessionformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionformationRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 * Count All
	 *
	 * @return Ambigous <\Doctrine\ORM\mixed, mixed, multitype:, \Doctrine\DBAL\Driver\Statement,
	 *		 \Doctrine\Common\Cache\mixed>
	 */
	public function count()
	{
		$qb = $this->createQueryBuilder('sf')->select('count(sf)');
		$query = $qb->getQuery();

		return $query->setCacheable('true')->useQueryCache(true)->useResultCache(true)->getSingleScalarResult();
	}

	/**
	 * Get Query for All Entities
	 *
	 * @return \Doctrine\ORM\Query
	 */
	public function getAllQuery()
	{
		$qb = $this->createQueryBuilder('sf')
			->join('sf.moduleformation', 'mf')
			->orderBy('mf.code', 'ASC')
			->addOrderBy('sf.code', 'ASC');
		$query = $qb->getQuery();

		return $query;
	}

	/**
	 * Get All Entities
	 *
	 * @return Ambigous <\Doctrine\ORM\mixed,
	 *		 \Doctrine\ORM\Internal\Hydration\mixed,
	 *		 \Doctrine\DBAL\Driver\Statement,
	 *		 \Doctrine\Common\Cache\mixed>
	 */
	public function getAll()
	{
		return $this->getAllQuery()->setCacheable('true')->useQueryCache(true)->useResultCache(true)
		->execute();
	}

	/**
	 * Count All
	 *
	 * @return Ambigous <\Doctrine\ORM\mixed, mixed, multitype:, \Doctrine\DBAL\Driver\Statement,
	 *		 \Doctrine\Common\Cache\mixed>
	 */
	public function countByModuleformation(Moduleformation $mf)
	{
		$qb = $this->createQueryBuilder('sf')->select('count(sf)')->join('mg.moduleformation', 'mf')->where('mf.id = :mfId')->setParameter('mfId', $mf->getId());
		$query = $qb->getQuery();

		return $query->setCacheable('true')->useQueryCache(true)->useResultCache(true)->getSingleScalarResult();
	}

	/**
	 * Get Query for All Entities
	 *
	 * @return \Doctrine\ORM\Query
	 */
	public function getAllByModuleformationQuery(Moduleformation $mf)
	{
		$qb = $this->createQueryBuilder('sf')
			->join('sf.moduleformation', 'mf')
			->where('mf.id = :mfId')
			->setParameter('mfId', $mf->getId())
			->orderBy('mf.code', 'ASC')
			->addOrderBy('sf.code', 'ASC');
		$query = $qb->getQuery();

		return $query;
	}

	/**
	 * Get All Entities
	 *
	 * @return Ambigous <\Doctrine\ORM\mixed,
	 *		 \Doctrine\ORM\Internal\Hydration\mixed,
	 *		 \Doctrine\DBAL\Driver\Statement,
	 *		 \Doctrine\Common\Cache\mixed>
	 */
	public function getAllByModuleformation(Moduleformation $mf)
	{
		return $this->getAllByModuleformationQuery($mf)->setCacheable('true')->useQueryCache(true)->useResultCache(true)
		->execute();
	}
}
